package abdmecdh

import (
	"encoding/base64"
	"testing"
)

// These were generated by the Java/BouncyCastle implementation.
const (
	requesterPrivateKey = "Dnh316gsSfP+0kiNmEgsIekLsY6BQr7b++3rHQ8otAI="
	requesterPublicKey  = "BBbWU1fw1y1ErdKasIoQKKAWzq3N9ARcrukg7b1MpD3RHi9ofFAFhyIwMIA5p+iMCcLHkzQRoEFvCpNET1+tFtQ="
	requesterNonce      = "5mLKfBzxPw5+xVgxHu/iG+mzw+xIVN1dSFDrqB/KkIE="

	senderPrivateKey = "BJig2akHxYJKjA/uyUSzVris72DsOt95vVaG2ZzGSDE="
	senderPublicKey  = "BDWu6EFsroAUi8lnWZmLZCDZT7XbpsdEC7eeEtNnseHkDKa0igaRxDQOKro7KBaivUiTxdfvRK0mVlVgWGyZo98="
	senderNonce      = "IEEtSc15HpLboL/kjBhu+K2Hqro/aoTh9HAgXA5JwMM="

	plaintext = ""

	encryptedData = ""
)

// TestDecryptWithKnownVector takes all pre-shared parameters (sender public key,
// sender nonce, receiver private key, receiver nonce, and encrypted data) and
// verifies that decryption produces the expected plaintext.
func TestDecryptWithKnownVector(t *testing.T) {
	tests := []struct {
		name               string
		senderPublicKey    string
		senderNonce        string
		receiverPrivateKey string
		receiverNonce      string
		encryptedData      string
		wantPlaintext      string
	}{
		{
			name:               "static vector from Java/BouncyCastle keys",
			senderPublicKey:    senderPublicKey,
			senderNonce:        senderNonce,
			receiverPrivateKey: requesterPrivateKey,
			receiverNonce:      requesterNonce,
			encryptedData:      encryptedData,
			wantPlaintext:      plaintext,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			decResp, err := Decrypt(DecryptionRequest{
				EncryptedData:       tt.encryptedData,
				RequesterNonce:      tt.receiverNonce,
				SenderNonce:         tt.senderNonce,
				RequesterPrivateKey: tt.receiverPrivateKey,
				SenderPublicKey:     tt.senderPublicKey,
			})
			if err != nil {
				t.Fatalf("decrypt failed: %v", err)
			}
			if decResp.DecryptedData != tt.wantPlaintext {
				t.Fatalf("plaintext mismatch\ngot:  %s\nwant: %s", decResp.DecryptedData, tt.wantPlaintext)
			}
		})
	}
}

func TestGeneratorPointOnCurve(t *testing.T) {
	if !isOnCurve(curveGx, curveGy) {
		t.Fatal("generator point G is not on the curve")
	}
}

func TestPublicKeyOnCurve(t *testing.T) {
	pubBytes, err := base64.StdEncoding.DecodeString(requesterPublicKey)
	if err != nil {
		t.Fatal(err)
	}
	x, y, err := unmarshalUncompressed(pubBytes)
	if err != nil {
		t.Fatal(err)
	}
	if !isOnCurve(x, y) {
		t.Fatal("requester public key is not on the curve")
	}
}

func TestEncryptDecryptWithJavaKeys(t *testing.T) {
	encResp, err := Encrypt(EncryptionRequest{
		StringToEncrypt:    plaintext,
		SenderNonce:        senderNonce,
		RequesterNonce:     requesterNonce,
		SenderPrivateKey:   senderPrivateKey,
		RequesterPublicKey: requesterPublicKey,
	})
	if err != nil {
		t.Fatalf("encrypt failed: %v", err)
	}

	decResp, err := Decrypt(DecryptionRequest{
		EncryptedData:       encResp.EncryptedData,
		RequesterNonce:      requesterNonce,
		SenderNonce:         senderNonce,
		RequesterPrivateKey: requesterPrivateKey,
		SenderPublicKey:     senderPublicKey,
	})
	if err != nil {
		t.Fatalf("decrypt failed: %v", err)
	}

	if decResp.DecryptedData != plaintext {
		t.Fatalf("plaintext mismatch\ngot:  %s\nwant: %s", decResp.DecryptedData, plaintext)
	}
}

// TestCrossImplGoEncryptJavaDecrypt encrypts with Go-generated sender keys
// and Java-generated requester keys, then decrypts with the Java requester private key.
func TestCrossImplGoEncryptJavaDecrypt(t *testing.T) {
	goSender, err := GenerateKeyMaterial()
	if err != nil {
		t.Fatalf("generate go sender keys: %v", err)
	}

	original := ""

	encResp, err := Encrypt(EncryptionRequest{
		StringToEncrypt:    original,
		SenderNonce:        goSender.Nonce,
		RequesterNonce:     requesterNonce,
		SenderPrivateKey:   goSender.PrivateKey,
		RequesterPublicKey: requesterPublicKey,
	})
	if err != nil {
		t.Fatalf("encrypt failed: %v", err)
	}

	decResp, err := Decrypt(DecryptionRequest{
		EncryptedData:       encResp.EncryptedData,
		RequesterNonce:      requesterNonce,
		SenderNonce:         goSender.Nonce,
		RequesterPrivateKey: requesterPrivateKey,
		SenderPublicKey:     goSender.PublicKey,
	})
	if err != nil {
		t.Fatalf("decrypt failed: %v", err)
	}

	if decResp.DecryptedData != original {
		t.Fatalf("plaintext mismatch\ngot:  %s\nwant: %s", decResp.DecryptedData, original)
	}
}

// TestCrossImplJavaEncryptGoDecrypt encrypts with Java sender keys
// and Go-generated requester keys, then decrypts with the Go requester private key.
func TestCrossImplJavaEncryptGoDecrypt(t *testing.T) {
	goRequester, err := GenerateKeyMaterial()
	if err != nil {
		t.Fatalf("generate go requester keys: %v", err)
	}

	original := "Orig"

	encResp, err := Encrypt(EncryptionRequest{
		StringToEncrypt:    original,
		SenderNonce:        senderNonce,
		RequesterNonce:     goRequester.Nonce,
		SenderPrivateKey:   senderPrivateKey,
		RequesterPublicKey: goRequester.PublicKey,
	})
	if err != nil {
		t.Fatalf("encrypt failed: %v", err)
	}

	decResp, err := Decrypt(DecryptionRequest{
		EncryptedData:       encResp.EncryptedData,
		RequesterNonce:      goRequester.Nonce,
		SenderNonce:         senderNonce,
		RequesterPrivateKey: goRequester.PrivateKey,
		SenderPublicKey:     senderPublicKey,
	})
	if err != nil {
		t.Fatalf("decrypt failed: %v", err)
	}

	if decResp.DecryptedData != original {
		t.Fatalf("plaintext mismatch\ngot:  %s\nwant: %s", decResp.DecryptedData, original)
	}
}

func TestRoundTrip(t *testing.T) {
	// Generate fresh keys for both parties
	requester, err := GenerateKeyMaterial()
	if err != nil {
		t.Fatalf("generate requester key material: %v", err)
	}
	sender, err := GenerateKeyMaterial()
	if err != nil {
		t.Fatalf("generate sender key material: %v", err)
	}

	original := "The secret is safe"

	// Encrypt
	encResp, err := Encrypt(EncryptionRequest{
		StringToEncrypt:    original,
		SenderNonce:        sender.Nonce,
		RequesterNonce:     requester.Nonce,
		SenderPrivateKey:   sender.PrivateKey,
		RequesterPublicKey: requester.PublicKey,
	})
	if err != nil {
		t.Fatalf("encrypt: %v", err)
	}

	// Decrypt
	decResp, err := Decrypt(DecryptionRequest{
		EncryptedData:       encResp.EncryptedData,
		RequesterNonce:      requester.Nonce,
		SenderNonce:         sender.Nonce,
		RequesterPrivateKey: requester.PrivateKey,
		SenderPublicKey:     sender.PublicKey,
	})
	if err != nil {
		t.Fatalf("decrypt: %v", err)
	}

	if decResp.DecryptedData != original {
		t.Fatalf("round trip failed\ngot:  %s\nwant: %s", decResp.DecryptedData, original)
	}
}

func BenchmarkGenerateKeyMaterial(b *testing.B) {
	for b.Loop() {
		_, err := GenerateKeyMaterial()
		if err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkEncrypt(b *testing.B) {
	req := EncryptionRequest{
		StringToEncrypt:    plaintext,
		SenderNonce:        senderNonce,
		RequesterNonce:     requesterNonce,
		SenderPrivateKey:   senderPrivateKey,
		RequesterPublicKey: requesterPublicKey,
	}
	for b.Loop() {
		_, err := Encrypt(req)
		if err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkDecrypt(b *testing.B) {
	encResp, err := Encrypt(EncryptionRequest{
		StringToEncrypt:    plaintext,
		SenderNonce:        senderNonce,
		RequesterNonce:     requesterNonce,
		SenderPrivateKey:   senderPrivateKey,
		RequesterPublicKey: requesterPublicKey,
	})
	if err != nil {
		b.Fatal(err)
	}
	req := DecryptionRequest{
		EncryptedData:       encResp.EncryptedData,
		RequesterNonce:      requesterNonce,
		SenderNonce:         senderNonce,
		RequesterPrivateKey: requesterPrivateKey,
		SenderPublicKey:     senderPublicKey,
	}
	b.ResetTimer()
	for b.Loop() {
		_, err := Decrypt(req)
		if err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkRoundTrip(b *testing.B) {
	for b.Loop() {
		requester, err := GenerateKeyMaterial()
		if err != nil {
			b.Fatal(err)
		}
		sender, err := GenerateKeyMaterial()
		if err != nil {
			b.Fatal(err)
		}

		encResp, err := Encrypt(EncryptionRequest{
			StringToEncrypt:    plaintext,
			SenderNonce:        sender.Nonce,
			RequesterNonce:     requester.Nonce,
			SenderPrivateKey:   sender.PrivateKey,
			RequesterPublicKey: requester.PublicKey,
		})
		if err != nil {
			b.Fatal(err)
		}

		_, err = Decrypt(DecryptionRequest{
			EncryptedData:       encResp.EncryptedData,
			RequesterNonce:      requester.Nonce,
			SenderNonce:         sender.Nonce,
			RequesterPrivateKey: requester.PrivateKey,
			SenderPublicKey:     sender.PublicKey,
		})
		if err != nil {
			b.Fatal(err)
		}
	}
}
